### PR TITLE
Add Project.toml

### PR DESCRIPTION
**Pull request by rofinn**
Adds Project.toml and removes REQUIRE files.

### CODE REVIEW

**Comment by dfdx** [comment]
I'm not quite sure the `script` section of `.travis.yml` is actually needed anymore - this looks like very old stuff, so we can try to remove it completely and see if it makes Travis happy.

**Comment by dfdx** [comment]
Looks good to me, @rofinn do you have anything to add or I can merge it?

**Comment by rofinn** [comment]
No, I think this should be good to go.

**Comment by dfdx** [comment]
@JuliaRegistrator register()

**Pull request merged**
